### ISSUE TITLE
Download script for NOAA atmospheric CO2 data

### ISSUE THREAD

**Issue by jessegrabowski** [jessegrabowski/laos-climate-change#21]
#5 identified the following dataset for use in our replication:

https://data.globalchange.gov/dataset/noaa-cmdl-co2_mm_gl

Write a script that checks if `data/noaa-cmdl-co2_mm_gl.csv` exists. If it doesn't it should download it, do the necessary preprocessing, and save it. Otherwise, load it from disk. 

Preprocessing should put it into a pandas dataframe with dates on the index and a single column. Dates should be `DateTime` objects with the correct frequency set (`YS-JAN`).

**Comment by andrewpwalters** [comment]
Added commit, will create PR for all of my data for this week
