### ISSUE TITLE
Remove EMDAT Data file

### ISSUE THREAD

**Issue by jessegrabowski** [jessegrabowski/laos-climate-change#3]
Rehosting the EMDAT data here is a violation of their TOS. It needs to be removed ASAP (delete from git history as well)

**Comment by CamSalda** [comment]
emdat file already deleted. I am having some issues deleting history. Will be checked with @jessegrabowski.

**Comment by jessegrabowski** [comment]
Make PR then I can show you how to do an interactive rebase to drop certain commits
