### ISSUE TITLE
Add environment.yaml

### ISSUE THREAD

**Issue by jessegrabowski** [jessegrabowski/laos-climate-change#8]
The project needs an environment file we, as well as any future researchers interested in reproduction, can use

**Comment by andrewpwalters** [comment]
Hi Jesse, can you please add pandas_datareader and wbdata? 

I will also prob have a few other data downloader packages to add by Mondy.

Andrew

**Comment by jessegrabowski** [comment]
What's the difference between `pandas_datareader.wb.WorldBankReader` and `wbdata`?

**Comment by andrewpwalters** [comment]
The latter was the first thing that came up when I googled how to pull WB data into python ;)

As you were, this makes sense. Some of the data sources I found don't have convenient ways to pull them in. Can I download the raw CSV and upload to a raw data folder? What's best practice here?

**Comment by jessegrabowski** [comment]
Use the `requests` package to directly download if possible. If we can't do that, we add a `data_sources.md` file with links. We should archive the pages as well so that our work is robust to changes to the external websites.

**Comment by jessegrabowski** [comment]
We should avoid hosting data on our repo if at all possible, because ideally whenever the external sources update, we can automatically get the newest stuff. If we REALLY can't find a better option we can download CSVs that are "sufficiently small"
